server:
  port: 8081

spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/demo20201123?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: toor
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
# 热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #设置重启的目录，添加目录的文件需要restart
      # 解决项目重新编译后接口报404的问题
      poll-interval: 3000
      quiet-period: 1000
## Ehcache缓存配置
  cache:
    ehcache:
      config: ehcache.xml
# mybaits配置
mybatis:
#  mapper的位置
  mapper-locations: classpath:/mappers/*.xml
#  指定POJO扫描包来让mybatis自动扫描到自定义POJO
  type-aliases-package:
  configuration:
#    下划线转驼峰
    map-underscore-to-camel-case: true

# pagehelper配置
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
# 显示执行sql
logging:
  level:
    com.kingwan.boot: debug

